name: Autoated tests

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: ensure browsers are installed
        run: python -m playwright install --with-deps
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest



